[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

# Do a full check of everything.
[tasks.complete-check]
dependencies = [
  "clean",
  "format",
  "check",
  "clippy",
  "test",
  "code-coverage",
  "docs",
  "build",
  "audit-flow",
  "outdated-flow"
]

# Run cargo-tarpaulin and output the test coverage.
[tasks.code-coverage]
workspace = false
command = "cargo"
args = [
  "tarpaulin",
  "--exclude-files=target/*",
  "--out=html",
  "--output-dir=coverage",
  "--skip-clean",
  "--target-dir=target/tarpaulin",
  "--workspace"
]
