# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "opml"
description = "An OPML parser for Rust."
authors = ["Holllo <helllo@holllo.cc>"]
version = "0.3.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Holllo/opml"
readme = "../README.md"
edition = "2018"
keywords = ["xml", "opml"]

[lib]
path = "source/lib.rs"

[dependencies]
regex = "1.3"
serde = { version = "1.0", features = ["derive"] }
strong-xml = "0.6"
thiserror = "1.0.24"
